[package]
name = "address_miner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.15.0"
ethers = "1.0.0"
ethers-core = "1.0.0"
ethers-signers = "1.0.0"